FROM golang:1.25-bookworm AS go

FROM node:22-bookworm

COPY --from=go /usr/local/go /usr/local/go

ENV GOPATH=/go
ENV PATH=/usr/local/go/bin:/go/bin:$PATH

RUN mkdir -p /go && corepack enable

WORKDIR /workspace
